CREATE TABLE futures_agg_trade_minute (
    symbol                         VARCHAR(20)     NOT NULL,
    minute_time                    TIMESTAMPTZ     NOT NULL,
    first_event_time               TIMESTAMPTZ     NOT NULL,
    last_event_time                TIMESTAMPTZ     NOT NULL,
    first_agg_trade_id             BIGINT          NOT NULL,
    last_agg_trade_id              BIGINT          NOT NULL,
    aggregate_trade_count          INTEGER         NOT NULL,
    underlying_trade_count         BIGINT          NOT NULL,
    base_volume                    NUMERIC(38, 12) NOT NULL,
    quote_notional                 NUMERIC(38, 12) NOT NULL,
    aggressive_buy_base            NUMERIC(38, 12) NOT NULL,
    aggressive_sell_base           NUMERIC(38, 12) NOT NULL,
    aggressive_buy_quote           NUMERIC(38, 12) NOT NULL,
    aggressive_sell_quote          NUMERIC(38, 12) NOT NULL,
    base_delta                     NUMERIC(38, 12) NOT NULL,
    quote_delta                    NUMERIC(38, 12) NOT NULL,
    first_price                    NUMERIC(30, 12) NOT NULL,
    last_price                     NUMERIC(30, 12) NOT NULL,
    minimum_price                  NUMERIC(30, 12) NOT NULL,
    maximum_price                  NUMERIC(30, 12) NOT NULL,
    buy_vwap                       NUMERIC(30, 12),
    sell_vwap                      NUMERIC(30, 12),
    max_aggregate_quote            NUMERIC(38, 12) NOT NULL,
    large_10k_count                INTEGER         NOT NULL,
    large_10k_buy_quote            NUMERIC(38, 12) NOT NULL,
    large_10k_sell_quote           NUMERIC(38, 12) NOT NULL,
    large_100k_count               INTEGER         NOT NULL,
    large_100k_buy_quote           NUMERIC(38, 12) NOT NULL,
    large_100k_sell_quote          NUMERIC(38, 12) NOT NULL,
    large_1m_count                 INTEGER         NOT NULL,
    large_1m_buy_quote             NUMERIC(38, 12) NOT NULL,
    large_1m_sell_quote            NUMERIC(38, 12) NOT NULL,
    agg_trade_id_gap_count         BIGINT          NOT NULL,
    duplicate_count                INTEGER         NOT NULL,
    kline_base_volume_difference   NUMERIC(38, 12),
    reconciliation_status          VARCHAR(20)     NOT NULL DEFAULT 'KLINE_MISSING',
    created_at                     TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at                     TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    PRIMARY KEY (symbol, minute_time),
    CHECK (aggregate_trade_count > 0),
    CHECK (underlying_trade_count > 0),
    CHECK (base_volume >= 0 AND quote_notional >= 0),
    CHECK (agg_trade_id_gap_count >= 0 AND duplicate_count >= 0),
    CHECK (reconciliation_status IN ('MATCHED', 'MISMATCH', 'KLINE_MISSING'))
);

CREATE TABLE futures_agg_trade_import (
    archive_name       VARCHAR(160) PRIMARY KEY,
    source_url         TEXT         NOT NULL,
    expected_sha256    CHAR(64)     NOT NULL,
    archive_size       BIGINT       NOT NULL,
    status             VARCHAR(20)  NOT NULL,
    minute_rows        INTEGER      NOT NULL DEFAULT 0,
    source_rows        BIGINT       NOT NULL DEFAULT 0,
    completed_at       TIMESTAMPTZ,
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CHECK (status IN ('DOWNLOADED', 'COMPLETED', 'FAILED'))
);
